"""Illness

Revision ID: 36a6ea51517d
Revises: 
Create Date: 2024-04-23 08:37:11.982338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a6ea51517d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illness',
    sa.Column('mkb10', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('mkb10')
    )
    with op.batch_alter_table('illness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_illness_mkb10'), ['mkb10'], unique=False)

    op.create_table('diagnosis',
    sa.Column('mkb10', sa.String(length=5), nullable=False),
    sa.Column('diagnosis_info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mkb10'], ['illness.mkb10'], ),
    sa.PrimaryKeyConstraint('mkb10')
    )
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_mkb10'), ['mkb10'], unique=False)

    op.create_table('therapy',
    sa.Column('mkb10', sa.String(length=5), nullable=False),
    sa.Column('therapy_info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mkb10'], ['illness.mkb10'], ),
    sa.PrimaryKeyConstraint('mkb10')
    )
    with op.batch_alter_table('therapy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapy_mkb10'), ['mkb10'], unique=False)

    op.drop_table('diagnosis')
    op.drop_table('illness')
    op.drop_table('therapy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy',
    sa.Column('mkb10', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('therapy_info', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mkb10'], ['illness.mkb10'], name='therapy_mkb10_fkey'),
    sa.PrimaryKeyConstraint('mkb10', name='therapy_pkey')
    )
    op.create_table('illness',
    sa.Column('mkb10', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mkb10', name='illness_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('diagnosis',
    sa.Column('mkb10', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('diagnosis_info', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mkb10'], ['illness.mkb10'], name='diagnosis_mkb10_fkey'),
    sa.PrimaryKeyConstraint('mkb10', name='diagnosis_pkey')
    )
    with op.batch_alter_table('therapy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapy_mkb10'))

    op.drop_table('therapy')
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_mkb10'))

    op.drop_table('diagnosis')
    with op.batch_alter_table('illness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_illness_mkb10'))

    op.drop_table('Illness')
    # ### end Alembic commands ###
